### ISSUE TITLE
Ace value does not change to 1 when hand value is  >= 11

### ISSUE THREAD

**Issue by SlimInc** [Himan10/BlackJack#1]
Hi, 

I am new to python and trying to learn.. First project is to build a blackjack game, so really enjoy your code, very impressive.
However I noticed that the value of an Ace does not change when the hand value is >= 11

![image](https://user-images.githubusercontent.com/43554025/70943763-e5ea5180-2051-11ea-85bb-71204d0bf285.png)

**Comment by Himan10** [comment]
@PythonStudyDK Hey, thanks man for the feedback .. I'll fix it in a couple of days and let you know.
if you've any suggestions or you faced some other errors then please tell. 
Thanks

**Comment by Himan10** [comment]
@PythonStudyDK Hey, I reconfigured adjust_for_ace() function and now it's possible to grow and shrink our Ace value ... Test it again and if you encounter any other issue then please let me know.
@ghazigamer Partner, you should check it as well ... it looks updated now.
